name: Node CI

on:
  push:
    branches:
      - master
      - esm-only
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: Test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['14.x']
        os: [
          ubuntu-latest,
          macOS-latest,
          # windows-latest,
        ]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1
        with:
          install-command: yarn

      - name: Test package
        run: yarn test
